spring.application.name=siw-festival

spring.jpa.database=POSTGRESQL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/festival
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=debug
logging.level.org.hibernate.type.descriptor.sql=trace
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

app.jwt.secret=siw-festival-chiave-di-firma-jwt-2026-uniroma3-cambiami
app.jwt.expiration-ms=86400000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

server.port=8080
spring.thymeleaf.check-template-location=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.thymeleaf.encoding=UTF-8
spring.web.locale=it
spring.web.locale-resolver=fixed

app.uploads.directory=uploads/posters
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
